CREATE DATABASE IF NOT EXISTS BANKING;

CREATE TABLE CUSTOMERS(
   CUSTOMER_ID INT PRIMARY KEY,
   CUSTOMER_NAME VARCHAR(50),
   MODE VARCHAR(50) NOT NULL,
   CITY VARCHAR(50)
);

ALTER TABLE CUSTOMERS
ADD CREDIT_SCORE INT;

SELECT * FROM CUSTOMERS;

INSERT INTO CUSTOMERS
(CUSTOMER_ID,CUSTOMER_NAME,MODE,CITY)
VALUES
(101,"DAVID","NETBANKING","WARANGAL"),
(102,"FATHIMA","CREDIT CARD","HYDERABAD"),
(103,"THARUN","UPI","HYDERABAD"),
(104,"KOUSHIK","NETBANKING","KHAMMAM"),
(105,"ROHAN","CREDIT CARD","DELHI"),
(106,"PRIYA","UPI","DELHI"),
(107,"SUNNY","CREDIT CARD","KHAMMAM"),
(108,"MAYA","UPI","WARANGAL"),
(109,"SANA","CREDIT CARD","HYDERABAD");

SELECT * FROM CUSTOMERS;

SELECT COUNT(MODE)
FROM CUSTOMERS;

SELECT MODE ,COUNT(CUSTOMER_ID)
FROM CUSTOMERS
GROUP BY MODE; 


INSERT INTO CUSTOMERS VALUES (110,"BLESSY","NETBANKING","WARANGAL");

SELECT * FROM CUSTOMERS 
WHERE MODE = "UPI";

SELECT MODE FROM CUSTOMERS
WHERE MODE = "NETBANKING";

SELECT * FROM CUSTOMERS 
WHERE MODE = "CREDIT CARD" AND CITY = "HYDERABAD";

SELECT * FROM CUSTOMERS 
WHERE MODE IN ("NETBANKING","CREDIT CARD") 
ORDER BY MODE;

SELECT CITY,COUNT(CUSTOMER_ID)
FROM CUSTOMERS
GROUP BY CITY
ORDER BY CITY;

SELECT MODE,COUNT(CUSTOMER_ID)
FROM CUSTOMERS
GROUP BY MODE
ORDER BY MODE;
